name: Bug Report
description: Report a bug in the slingshot-operator
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Deploy CXIDriver with config...
        2. Wait for...
        3. Observe error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Operator Version
      description: What version of the operator are you running?
      placeholder: v1.0.0
    validations:
      required: true

  - type: input
    id: k8s-version
    attributes:
      label: Kubernetes Version
      description: Output of `kubectl version`
      placeholder: v1.30.0
    validations:
      required: true

  - type: textarea
    id: cxidriver
    attributes:
      label: CXIDriver Configuration
      description: Your CXIDriver resource YAML (redact sensitive info)
      render: yaml

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Controller logs, events, or other relevant output
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
